# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
Z = np.random.random((3,3,3))
print(Z)

[[[0.17608938 0.0848208  0.0011401 ]
  [0.96210117 0.59500165 0.01110224]
  [0.57208603 0.78944186 0.2914468 ]]

 [[0.51564285 0.19357581 0.42926759]
  [0.23984968 0.87318692 0.70304715]
  [0.03719196 0.98212271 0.55680073]]

 [[0.71666051 0.7546349  0.60027271]
  [0.77252036 0.15845287 0.19725298]
  [0.44914194 0.78940336 0.95463047]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.81239525  0.21106534 -1.08538934  1.33174398  1.13793536]
 [-1.11053518 -1.03114668  0.8671214   0.05185685  1.54053183]
 [-0.40679018  1.44908002 -0.39281838 -1.12979494  1.08514307]
 [-0.13141244  1.42177865  1.41039429  0.33769718 -1.53682805]
 [-0.99377229 -1.07072571 -0.96524864 -0.376564    0.19907311]]


# 5.  How to find common values between two arrays?

In [6]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-11-16
2020-11-17
2020-11-18


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.3873698  0.         0.7528505  0.32629237 0.17577337 0.26131278
 0.12477749 0.01184757 0.05853724 0.43834635]


# 9. How to print all the values of an array?

In [10]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [11]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.11743633 -0.32548563 -0.08959167  0.22310192  0.40500072 -0.30788547
  -0.56470771  0.32046675  0.38850124 -0.16683648]
 [-0.02944195  0.2295738   0.00144623 -0.01742337 -0.20105253  0.34973274
   0.35546806 -0.17689925 -0.36714598 -0.14425776]
 [-0.09621507  0.26144301 -0.32746804 -0.23569063  0.2366349   0.09737478
   0.29139636  0.31060694 -0.28012991 -0.25795235]
 [ 0.46093752 -0.37125746 -0.4125796   0.55008879 -0.31708725  0.3370496
   0.22715477  0.28371313 -0.41706472 -0.34095478]
 [-0.30006492  0.21698192  0.40752641  0.08317337  0.08682404 -0.08217359
   0.06531394 -0.36919025 -0.26944997  0.16105905]]
[[ 0.11743633 -0.32548563 -0.08959167  0.22310192  0.40500072 -0.30788547
  -0.56470771  0.32046675  0.38850124 -0.16683648]
 [-0.02944195  0.2295738   0.00144623 -0.01742337 -0.20105253  0.34973274
   0.35546806 -0.17689925 -0.36714598 -0.14425776]
 [-0.09621507  0.26144301 -0.32746804 -0.23569063  0.2366349   0.09737478
   0.29139636  0.31060694 -0.28012991 -0.25795235]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 6. 2. 3. 5. 1. 4. 1. 3.]


In [13]:
np.add.at(Z, I, 1)
print(Z)

[ 5.  3. 11.  3.  5.  9.  1.  7.  1.  5.]


# 12.How to get the diagonal of a dot product?

In [14]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.35080907 0.15107827 0.4596026  0.96465978 0.07830062]
 [0.68643574 0.58332067 0.27347041 0.58649641 0.80397874]
 [0.30972642 0.7662991  0.28906293 0.68266884 0.50927339]
 [0.52107672 0.87575667 0.79819441 0.24859635 0.08334695]
 [0.58458077 0.22430169 0.85629421 0.88501425 0.5513439 ]]
[[0.79261582 0.97498842 0.7475866  0.04216448 0.35846029]
 [0.2541575  0.56582146 0.08613492 0.48918724 0.92753278]
 [0.79111967 0.58278493 0.40155621 0.80645338 0.65301077]
 [0.07172573 0.23623511 0.8923584  0.28836516 0.99785668]
 [0.04500392 0.43275948 0.60268685 0.9785598  0.75732257]]
diagonal of a dot product method 1 is.... [0.75276991 1.64517716 1.32974509 1.247333   2.27742807]
diagonal of a dot product method 2 is.... [0.75276991 1.64517716 1.32974509 1.247333   2.27742807]


# 13.How to find the most frequent value in an array?

In [15]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[3 7 9 4 7 3 3 7 6 3 7 5 5 2 8 5 2 0 8 4 3 6 2 7 7 0 0 8 2 9 4 6 3 7 4 9 3
 0 0 0 0 1 7 3 5 5 2 6 9 0]
0


# 14.How to get the n largest values of an array

In [16]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [17]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
